model_name: DTS
data_name: btcv
data_path: /your/path/to/BTCV
image_size: 96
spatial_size: 96
sliced: false
lr: 2e-4
weight_decay: 1e-4
noise_ratio: 0.7
scheduler: true
warmup_epochs: 100
timesteps: 1000
classes: cfg/classes/btcv.yaml
device: cuda:0
model_path: null
pretrained_path: null  # pretrained/swin_unetr/model_swinvit.pt
max_epochs: 20000
val_freq: 1000
save_freq: 200
batch_size: 1
sw_batch_size: 2
overlap: 0.25
num_workers: 2
device_ids: null
project_name: DTS
wandb_name: null
log_dir: DTS
losses: mse,bce,dice
loss_combine: sum
include_background: false
label_smoothing: k-nls
smoothing_alpha: 0.1
smoothing_order: 1
lambda_decay: 0.05
extract_features: false
freeze: false
use_wandb: true
use_amp: false
use_cache: true